CREATE TABLE DMAAP_NOTIFICATIONS(
	notification TEXT PRIMARY KEY NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE BUFFERED_NOTIFICATIONS(
	notification TEXT PRIMARY KEY NOT NULL,
        cluster_id TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE CLUSTER_DETAILS(
	cluster_id TEXT PRIMARY KEY NOT NULL,
	cluster_info TEXT NOT NULL,
	child_thread_id BIGINT UNIQUE NOT NULL
);
CREATE TABLE CELL_INFO(
	cell_id TEXT PRIMARY KEY NOT NULL,
	pnf_name TEXT NOT NULL
);
CREATE TABLE PCI_REQUESTS(
	transaction_id TEXT PRIMARY KEY,
	child_thread_id BIGINT UNIQUE NOT NULL
);
CREATE TABLE FAULT_NOTIFICATIONS(
	notification TEXT PRIMARY KEY NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE PERFORMANCE_NOTIFICATIONS(
	notification TEXT PRIMARY KEY NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE HANDOVER_METRICS(
	src_cell_id TEXT PRIMARY KEY NOT NULL,
	ho_details TEXT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);		
CREATE TABLE PCI_UPDATE(
	cell_id TEXT PRIMARY KEY NOT NULL,
	old_pci BIGINT NOT NULL,
    new_pci BIGINT, 
    negative_ack_count INT DEFAULT 0
);
CREATE TABLE FIXED_PCI_CELLS(
	cell_id TEXT PRIMARY KEY NOT NULL,
	fixed_pci BIGINT NOT NULL,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
