version: '2.4'
networks:
  sonhms-default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
services: 
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - sonhms-default
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "kafka"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - sonhms-default
  dmaap:
    image: nexus3.onap.org:10001/onap/dmaap/dmaap-mr:1.1.8  
    ports:
      - "3904:3904"
      - "3905:3905"
    volumes:
      - ./config/dmaap/MsgRtrApi.properties:/appl/dmaapMR1/bundleconfig/etc/appprops/MsgRtrApi.properties
    depends_on:
      - zookeeper
      - kafka
    networks:
      - sonhms-default
  postgres:
    image: 'postgres:12-alpine'
    container_name: sonhms-postgres
    hostname: postgres
    environment:
     - POSTGRES_USER=sonhms_admin
     - POSTGRES_PASSWORD=postgres
     - POSTGRES_DB=sonhms
    ports:
     - 5432
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "5432"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
     - sonhms-default
  sonhms:
    image: "nexus3.onap.org:10001/onap/org.onap.dcaegen2.services.son-handler:latest"
    container_name: sonhms
    hostname: sonhms
    environment:
     - STANDALONE=true
     - CONFIG_FILE=/etc/config_all.json
    ports:
     - "8080:8080"
    volumes:
     - ./config/sonhms/config_all.json:/etc/config_all.json
    depends_on:
     - postgres
    networks:
     - sonhms-default    
    
